-- Generado por scripts/generate-seed-sql.mjs — no editar a mano
begin;
insert into public.roadmap_secciones (id, titulo, orden) values ('s1', 'MODIFIICACIONES URGENTES - IMPORTANTES (Errores o fallas funcionales o cosas mega indispensables)', 1);
insert into public.roadmap_secciones (id, titulo, orden) values ('s2', 'MODIFICACIONES URGENTES - NO IMPORTANTES (Necesarias para implementar)', 2);
insert into public.roadmap_secciones (id, titulo, orden) values ('s3', 'PROXIMAS MODIFICACIONES (No necesarias para implementar)', 3);
insert into public.roadmap_secciones (id, titulo, orden) values ('s4', 'PROXIMOS DESARROLLOS', 4);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T01', 's1', 'Idealista', 'Integración Idealista pedidos', 'Integracion idealista pedidos.
· Probar sistema con mail nuestro y testear, y testeado implementar sacando inmovilla.
· Hacer excel con historico todos los pedidos para poder meterlos y planificar la metida en el sistema.', 'Toni', 'Pendiente', '', 'ya implemente los usuarios y los mails, vamos a ir ajustando el algoritmo', null, '[]'::jsonb, 1);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T02', 's1', 'Agenda / Visitas', 'Sistema para agendar visitas con Google', 'la dinamica seria. El lead entra o puede ser un lead qeu ya entro yle comparti un piso y quiere visitarlo. De cualquier forma, el usuario tendra que agendar la visita. -------------- aca el usuario iria a acciones del piso dentro de ese lead y apretaria agendar visita--- Se le abriria un campo donde pueda apuntar (', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 2);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T03', 's1', '', 'leads nuevos', 'Los leads de ayer nuevos estan apareciendo aunque hayan sido gesrionados ayer como nuevos sin gestionar en rojo — incluso se da el caso en que me aparece cartel rojo de lead nuevo sin gestionar cuando esta  gestionado en la columna de gestion.  - Ademas, en el comentario que viene desde idealista, estaria bueno que se aclare en la lista de comentarios cuando se introduce algo como (( mensaje via idealista" hola, me gustaria consutltar por el pios bla bla "))) para que sea mas clari  ---- Tambien se dio el caso de que aparecian los lead que llegaron de idealista directamente como gestionados cuando entraban. seguramente por el comentario que se asento cuando entro via idealista. ', 'Toni', 'Pendiente', '', '', null, '[]'::jsonb, 3);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T04', 's1', '', 'leads nuevos que no reconoce piso', 'cuando sistema entra lead cuyo piso por el que solicito no reconoce crea un piso nuevo entonces en propiedades se crearon algunos que no corresponden y ademas el la lista de pisos dentro del lead no aparece marcheado con el que deberia si no con uno inventado por el sistema. Ademas deberiamos ver por que sistema no entiende que arago es arago en el caso del lead que te adjunto foto ', 'Toni', 'Pendiente', 'img 2', '', null, '[]'::jsonb, 4);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T05', 's2', 'Vistas y filtros', 'Vistas de trabajo por prioridad / match / estado / gestión / piso', 'Ver temas y formas de trabajo POR PRIORIDAD; POR MATCH; POR ESTADO; POR GESTIÓN; POR PISO. Cada vista me tiene que decir los que tienen pendiente gestión o tarea pendiente, en rojo.', 'Loro', 'Pendiente', '', 'Ya lo hice revisadlo', null, '[]'::jsonb, 5);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T06', 's2', 'Matching', 'Matching implícito (match provisorio automático)', 'Seria importante empezar a llamar a brifing "demanda" para adaptarnos al idioma local. jeje. el brifing implicito estaba pensando que en lugar de rojo, para que no moleste al verlo podria aparecer tal cual aparece ahora. gris claro. como pendiente de rellenar. tanto en la parte de los campos del brifing como en la parte de los campos del brifing cuando el lead esta plegado.. y que el sistema ya trabaje con esos valores para matchear. Luego si el cliente pone un valor se escribe en negrito normal xd lol ', 'Toni', 'Pendiente', '', '', null, '[]'::jsonb, 6);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T07', 's2', 'Capasitacion', 'Loom', 'Hacer loom explicativos para los chicos mostrando como funciona el sistema parte por parte y despues reunion para dudas y anotar las dudas para agregarlas a planing de capasitaciones ', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 7);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T08', 's2', '', 'UxUi filtros', 'mejorar el planteo de la ux de carga de filtros. presentar propuesta a toni que sea intuitiva ', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 8);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T09', 's2', '', 'Panel de leads', 'seria interesante que arriba del recuadro donde apareccen los leads el sistema te diga la cantidad de resultados encontrados siempre. ADJUNTO IMAGNE DE DONDE ', 'Toni', 'Pendiente', 'img 1', '', null, '[]'::jsonb, 9);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T10', 's2', '', 'filtros vistas', 'resulta un poco confuso cuando vemos las oportunidades entender que un numero corresponde a la cantidad que hay de oportunidades, o rojos o etc y otro numero a los pendientes. dejar solo el de pendientes mejor no? y que se vea rojo para que se entienda que tiene  -- aca tambien deberiamos ver ', 'Toni', 'Pendiente', '', '', null, '[]'::jsonb, 10);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T11', 's2', '', 'columna derecha comentarios + tareas + perfil', 'proponer nuevo diseño de las tres cosas integradas para que sea cvisualmente mas intuitivo porque ahora mismo se hace muy confuso entender esta parte ', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 11);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T12', 's2', '', 'color lead en izquierda  de la fila', 'seria bueno que borremos el color del lead a la izquierda de la fila. esto fue mala mia pero entorpece la visual y no aporta valor realmente ', 'Toni', 'Pendiente', '', '', null, '[]'::jsonb, 12);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T13', 's2', '', 'Puntito azul del lead en el que se esta trabajando', 'el puntito azul que estamos usando ahora esta bueno pero realmente es muy sutil y incuso a mi sabiendo lo que representa y habiendo recibido esas info explicita me cuesta. podriamos buscar otra forma de resaltarlo? resaltando el cuadro de la fila o o algo asi ', 'Toni', 'Pendiente', '', '', null, '[]'::jsonb, 13);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T14', 's3', '', 'mensajes predeterminadso', 'En el mensaje predeterminado estaruia bueno que el nombre lo incruste la IA. Entonces redactas el mensaje que queres. Tenes una lista en plan check list de los datos del sistema que queres que la ia te incruste en el mensaje y si los tildas la ia en el mensaje que vos redactastre te incrusta nombre, apellido, ibi, comunidad, link del anuncio etc etc etc entonces el usuario no tiene que lidiar con corchetes ni cosas raras ', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 14);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T15', 's3', 'Brifing', 'Brifing', 'hacer sistemas para brifear -brifing con link, brifing con txt y respuyesta en texto para meter en campo con IA directamente y que se rellene, brifing con bot ', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 15);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T16', 's3', 'Integración pedidos', 'Cranear cómo va a funcionar la integración de pedidos', 'Cranear como va a funcionar la integracion de pedidos... (del historial de la base de datos) para gestionarlos y publicitarles que pisos a nombre de que usuario, y que usuario se les asgnrara cada piso.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 16);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T17', 's3', 'Personal Shopper', 'Registro de clientes que vengan de personal shoppers', 'Ver como se registrarian clientes que vengan de parte de personal shoppers.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 17);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T18', 's3', 'Mensajería / WhatsApp', 'Protocolizar mensaje para cruzar varios pisos', 'Protocolizar mensaje para cruzar otros pisos ademas del que coordino visita por su consulta. Todos en un mensaje unido, varios pisos que puedan encajarle.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 18);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T19', 's3', 'UX / Carga de pisos', 'Mejorar UX de la carga de pisos', 'Mejorar Ux de la carga de pisos. Primero loro tiene que ver tema diseño y funcionalidad para optimizarlo. Que haya boton de carga via crm y boton de carga via idealista.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 19);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T20', 's3', 'Leads', 'Quitar el desplegable de estado del piso al cargar el lead', 'Sacar, cuando se carga el lead, el desplegable para elegir el estado del piso.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 20);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T21', 's3', 'UX / Columna gestión', 'Iconos de gestión y agenda sin columna extra', 'Brodix: aca, para no hacer una columna con tareas que agrega mucho espacio con poca informacion, yo lo pensaba mas como el icono ese al lado de el posponer (el relojuito de gestion) pegado, sin una columna extra. Al final es parte de lo mismo.
En la columna de gestion vos ves si esta pendiente o gestionado. Ves si queres posponer la gestion (eso se podria hacer que la palabra «posponer» aparezca solo cuando pones el cursor arriba, para que solo se vea el reloj) y la agendita al lado solo si hay una tarea agendada. Si no hay tarea agendada, nada.
Si la tarea esta vencida, la agendita tiene que aparecer roja para marcar que esta vencida.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 21);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T22', 's3', 'UX / Leads', 'Línea de color del lead más gruesa', '¿Podemos hacer la linea de color del lead a la izquierda mas gruesa para que sea mas notorio el color del lead?', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 22);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T23', 's3', 'Perfil cliente', 'Perfil del cliente dentro del desplegable', 'Ver dentro del desplegable que el perfil del cliente aparezca: nombre, telefono usuario (el que esta cargado), telefono alternativo si hay otro, y una parte de notas para poder poner cualquier cosa que se quiera poner de notas sobre el cliente. «Es una familia», «tiene que vender dos pisos en francia» o lo que sea.', 'Loro', 'Pendiente', '', '🔴 LORO: ver de mandar exactamente como tiene que ser.', null, '[]'::jsonb, 23);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T24', 's3', 'Gestión / Comentarios', '¿Exigir comentario para marcar como gestionado?', 'Pensar si no es bueno exigir comentario para marcar como gestionado, y que cambios de estado se añadan como comentarios.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 24);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T25', 's3', 'Feedback visitas', 'Sistema de feedback de visitas', 'Sistema de feetback visitas. Si esta en visitado hay que sacarlo cuanto antes:
1 Solicitar a usuario feetbacj post visita por ws.
2 Solicitar a cliente feetback por ws.
3 Insisitir a usuario.
4 Avisar a usuario que si cliente no responde mas de 3 veces, descarta piso.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 25);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T26', 's3', 'Mensajería / WhatsApp', 'Botón de resumen de pisos en un solo mensaje', 'Hacer boton para enviar resumen de pisos que pueden encajarle al cliente en un solo mensaje.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 26);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T27', 's3', 'Briefing / IA', 'Campo de IA al principio del briefing (renombrar a DEMANDA)', 'Como idea para pensar: ¿si campo de IA aparece al principio del brifing y podemos agregar todo con IA? Zona, comentarios extras, presupeusto, mensajes del cliente copiados y pegados, y que ia interprete y llene brifing en general y listo. Seria mucho mas intuitivo y practico. Y que lo que agregas en ese campo se introduzca donde corresponde y se borre.
—- Tambien cambiar mensaje de «brifing» a DEMANDA.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 27);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T28', 's3', 'Perfil cliente', 'Perfil ampliado en el desplegable superior izquierdo', 'Seria bueno que dentro del desplegable, arriba a la izquierda, salga perfil del cliente con notas del perfil, brifing hipotecario y datos de contacto mas amplios que solo el telefomno. Ademas, que se pueda configurar el contacto principal para que se ponga el que tiene whatsapp ahi.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 28);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T29', 's3', 'Funnel', 'Pisos «en limbo»: sacarlos del funnel a pendiente match', 'Ojo con los pisos que quedan en un limbo de que solicitaron por un piso y visitaron y nunca avanzan en el funnel. ¿Como los sacamos del funnel para que caigan a pendiente match automaticamente y se haga el trabajo de matching? Y a los clientes que tienen match en curso, ¿se les trabajara para matchearle pisos tambien?', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 29);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T30', 's3', 'Estados', 'Estados múltiples por piso y detalle al pasar el cursor', 'Cuando aparece el estado visitado en seguimiento, el proximo piso que agendo, el estado no es agendado. ¿Seria prodente hacer aparecer varios estados con el piso al cual se asocia ese estado? ¿O mostrar el mas avanzado como principal y los estados anteriroes como estados anexos?
—- Para empezar seria bueno que, al poner cursor arriba de estados, se pueda ver detalle de estados del cliente con cada piso. Ademas quizas que en la parte de estados te muestre todos, y con cada piso cual tiene.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 30);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T31', 's3', 'UX / Leads', 'Reemplazar el puntito azul por un recuadro remarcado', 'El puntito ese azul seria bueno remplazarlo por un recuadro remarcado en el lead para que se vea claro.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 31);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T32', 's3', 'UX / Estados', 'Estados de los pisos más claros en el desplegable', 'Tenemos que mejorar la UX para que los estados de los pisos en el desplegavle se vean claros.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 32);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T33', 's3', 'Filtros', 'No cerrar la ficha al cambiar de estado dentro de un filtro', 'El tema de cuando cambio de estado un piso y se me cierra porque estoy en un filtro que no contiene a ese piso: esta dificil y no esta bueno, porque quizas quiero ponerle un comentario o algo y no me deja.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 33);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T34', 's3', 'Funnel', 'Distinguir visualmente pisos con match y sin match', 'Visualmente, en el funnel, distinguir los pisos que tienen matrch de los que no tienen match. Para que sea mas pedagogico.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 34);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T35', 's3', 'UX / Carga de pisos', 'Botón carga piso desde CRM y desde Idealista', 'Poner boton carga piso desde crm y boton carga piso desde idealista.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 35);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T36', 's3', '', 'Cruce pisos lead nuevo', 'Programar agenda predeterminada de tarea de enviar a cliente pisos que puedan encajarle justo despues de agendar la visita ', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 36);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T37', 's3', '', 'Funnel ventas', 'deslpazar un poquito en la reprecentacion del funnel a la derecha lo que esta matcheado con un piso para que la gente netienda conceptualmente vierndo que todo eso es matcheado ', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 37);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T38', 's4', 'Estadísticas / Informes', 'Estadísticas de pisos, agentes y descartes', 'Estadisticas sobre los pisos y los agentes. Estadisticas motivos de descarte pisos, estadisticas portales, informes de comercializacion de pisos, informes para cita gestion, informes para rebajas, estadisticas de trabajo del empleado, estadisticas de descarte de lead… estadisticas muchas.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 38);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T39', 's4', 'Fotos / IA', 'Procesado masivo de fotos con IA y ordenación', 'Sistema para pasar fotos masivamente por IA, con prompts puestos para cada foto y uno puesto en general para todas las fotos juntas.
—- Tambien sistema para ordenar las fotos de forma ultra archi facil.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 39);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T40', 's4', 'Catastro / IA', 'Herramienta de uso de Catastro con IA', 'Herramienta de uso de catastro con IA.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 40);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T41', 's4', 'Portal / Red', 'PORTAL INMOBILIARIO + RED INMOBILIARIA + agente IA', 'PORTAL INMOBILIARIO + RED INMOBILIARIA + agente con IA (maneja sms, whatsapp y mail).
Deberia haber dos opciones: que toda la info la gestione internamente el crm, o participar de propelialista, que es la red de venta con portal propio con mas potencial de españa. Basicamente es un super bot que es personal shopper con todos los pedidos de la red, los que entran por el portal y los pisos de toda la red, y permanentemente esta optimizandose para convertir lo mas rapido y mejor posible.
En el portal, que se manejen videos en plan tik-tok para fomentar consumo y revolucionar la forma de mostrar los pisos, resumiendo imagenes, descripcion y etc en un video corto mas consumible.
IMPORTANTE que esté la base de la lógica muy bien planteada: cada lead se tiene que caer por tiempo de la escalera de estados, a menos que el usuario renueve su vigencia en ese estado a mano. Si no, se cae y va automáticamente a pendiente match. Los pendiente match se trabajan masivamente con bot para encajarles pisos. Los clientes que están en escalera, aún ver de cranear bien cómo trabajarlos con IA, o si permitir detener la promoción de pisos a estos si avanzan o si muestran interés.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 41);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T42', 's4', 'Portales', 'Publicar/despublicar automático en Idealista y Fotocasa', 'Sistema que publica y despublica en idealsita y fotocasa para optimizar pedidos. Tambien que optimiza las publis y da consejos.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 42);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T43', 's4', 'Web cliente', 'Web para la inmobiliaria usuaria con portal integrado', 'Desarrollo de pagina web para la inmobiliaria usuaria con IA, con portal inmobiliario integrado. O pagina de portal inmobiliario para que integren en su pagina web directamente.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 43);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T44', 's4', 'Automatizaciones', 'Secuencia completa de automatizaciones del funnel', 'Automatizacion:
1 Cuando entra el lead, que agende la visita.
2 Cuando se agenda visita, mensaje de confirmacion.
3 Dia de la visita, mensaje de recordatorio y posible documento de reconocimiento de visita.
4 Feedback visita.
5 Sistema de briefing transversal a todas las acciones.
6 Sistema de promocion de pisos automaticamente a leads.
7 Sistema de campañas para nuevos pisos, pisos rebajados, pisos con informacion/fotos nuevas, etc.
—- Agente: seria bueno que este pensado para automaticamente impulsar a todos los leads a avanzar en la etapa del funnel. Entonces que nada se pierda y que avance si el comercial no lo avanza.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 44);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T45', 's4', 'Briefing', 'Botón para copiar/enviar briefing', 'Boton en la parte de briefing para copiar link de briefing con formulario, copiar txt de briefing, o mandar a bot a brifiar.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 45);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T46', 's4', 'Historial', 'Acciones que disparen comentarios automáticos al historial', 'Acciones: estaria bueno que disparen comentarios al historial de comentarios. «Se agendo visita a tal piso», «se compartio tal piso», etc. Para que vaya quedando registro de todo. Incluso si se brifio, quedaria registro.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 46);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T47', 's4', 'Informes / IA', 'Generador de informes con IA y branding', 'Informes con IA. Interface donde cada uno de los informes tiene su lugar: informe de valoracion, informe de tal, informe de cual. Y podes trabajar con Claude pidiendole modificaciones y diseñando informes con todo el material visual de la empresa. Documentos mega archi profesionales, como los que entrego yo. Con la posibilidad de usar el anterior para hacer el nuevo, dejar fijado un modelo, y modificar hoja por hoja con prompts distinguidos.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 47);
insert into public.roadmap_tareas (id, sec_id, modulo, tarea, expl, resp, estado, img, com, fecha, files, orden) values ('T48', 's4', 'Soporte', 'Bot de soporte dentro del CRM o por WhatsApp', 'Bot de soporte dentro del crm o por ws que te ofrezca, desde el crm, ir a whatsapp a hablar para: reclamos de cosas que no funcionan, sugerencias de mejoras, cosas que podrian funcionar mejor, ideas, etc.', 'Loro', 'Pendiente', '', '', null, '[]'::jsonb, 48);
commit;
